### ISSUE TITLE
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?                           

### ISSUE THREAD

**Issue by Mudb0y** [digitalec/deemon#103]
I'm getting the following error while trying to run Deemon with pipx and Python-3.13:
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

**Comment by digitalec** [comment]
This appears to be due to Python 3.12 removing some deprecated importlib stuff, such as ImpImporter.

I’ll look at this when I can, but in the meantime, try upgrading setuptools to the latest and try again (remove version requirement from requirements.txt).

**Comment by digitalec** [comment]
Resolved in 714b96c
