### ISSUE TITLE
Like the idea...

### ISSUE THREAD

**Issue by bonelifer** [digitalec/deemon#104]
Like the idea, don't understand how to config it.

**Comment by Breakingx** [comment]
System?

**Comment by bonelifer** [comment]
Xubuntu 22.04. Have it installed. There's no real documentation on what to do.

**Comment by digitalec** [comment]
@bonelifer Did you read the several pages of documentation posted on the main page of this repo? You can also use `--help` on just about any command for more info.

**Comment by bonelifer** [comment]
Figured it out. Just a case of late night brain fog.
