### ISSUE TITLE
Cron cannot find the install location

### ISSUE THREAD

**Issue by mon5termatt** [digitalec/deemon#106]
/bin/sh: 1: /root/.local/bin/deemon: not found

i feel like this is something simple but i just copied the example file from the docs

**Comment by digitalec** [comment]
If you're getting `not found`, then deemon is not installed there. I would run `which deemon` and copy the output for cron.

**Comment by mon5termatt** [comment]
> If you're getting `not found`, then deemon is not installed there. I would run `which deemon` and copy the output for cron.

Will do.
