### ISSUE TITLE
Nothing is downloading after running `deemon refresh`

### ISSUE THREAD

**Issue by relink2013** [digitalec/deemon#115]
I am running the deemon docker container, along with [this](https://github.com/bambanah/deemix) fork of Deemix. 

I have several artists set to be monitored, and I set `"release_max_age": 0,` in `config.json`. 

According to the docs I would have expected this config to cause the entire discography for all monitored artists to be downloaded after a refresh, but it is not downloading anything at all. 

The only way I am able to get downloads going is by running `deemon download --monitored` then it downloads everything perfectly fine. That was until I realized every time I run that command it re downloads everything...

Below is my config:
```
{
    "check_update": 1,
    "debug_mode": false,
    "release_channel": "stable",
    "query_limit": 5,
    "smart_search": true,
    "rollback_view_limit": 10,
    "prompt_duplicates": false,
    "prompt_no_matches": false,
    "fast_api": true,
    "fast_api_threads": 25,
    "exclusions": {
        "enable_exclusions": true,
        "patterns": [],
        "keywords": ["live", "instrumental"]
    },
    "new_releases": {
        "release_max_age": 0,
        "include_unofficial": false,
        "include_compilations": false,
        "include_featured_in": true
    },
    "global": {
        "bitrate": "128",
        "alerts": false,
        "record_type": "all",
        "download_path": "/downloads",
        "email": ""
    },
    "deemix": {
        "path": "/deemix",
        "arl": "its-a-free-one-you-dont-want-it-anyway",
        "check_account_status": false,
        "halt_download_on_error": false
    },
    "smtp_settings": {
        "server": "",
        "port": 465,
        "starttls": false,
        "username": "",
        "password": "",
        "from_addr": ""
    },
    "plex": {
        "base_url": "",
        "ssl_verify": true,
        "token": "",
        "library": ""
    }
}
```

**Comment by digitalec** [comment]
The purpose of `refresh` is to refresh your existing artists and download all *new* releases since the last refresh. Monitoring an artist automatically performs a refresh to grab an initial baseline.

You can also use `refresh --time-machine YYYY-MM-DD` to perform a refresh from a date in time. For example, 1980-01-01 will grab any new release after 1980-01-01.

**Comment by relink2013** [comment]
I don't mean to comment on a closed issue, but just so I'm clear on how it works. Even though I have `"release_max_age": 0,` deemon is still not going to go "backwards" and download older releases? The way the docs read, I thought that would have been the case. 

If I add a brand new artist that I have no music from at all, and I want to grab the entire discography then just running `deemon refresh` while having `"release_max_age": 0,` wont cut it?  

If thats the case would running a single `deemon download --artist-id 100` when adding a new artist, and periodically running `deemon refresh` from there on out do what I'm after?

**Comment by digitalec** [comment]
No problem at all!

releases_max_age is how old deemon should consider a newly discovered release as *new*. Sometimes tracks become available well after their original release date (adding older items from their catalog). In these situations, you might not want something downloaded when it’s not technically new (newly available vs new release).

What you are likely looking for is `monitor -D ArtistName`. This will add the artist to monitor and queue their entire available discography (respecting your record_type setting) for download with deemix.

The purpose of deemon is to monitor artists and then run a scheduled task/cron job to occasionally refresh and grab the new releases.

Feel free to comment back if you need additional help.

**Comment by relink2013** [comment]
Ahhh, fantastic I will give that a go. how can I use that the with artistID? Deezer is horribly organized as it is, so I exclusively use artist ID's to try and prevent issues. 


Side question, I can put this in a new issue if needed.  

I have my exclusions setup like this:
```
"exclusions": {
        "enable_exclusions": true,
        "patterns": [],
        "keywords": ["live", "instrumental"]
    },
```
And I do see tons of albums being excluded because of that filter. But I am also still getting tons of them too. Is there a better way I could have set that filter up?
