### ISSUE TITLE
Artist Directory / Templates

### ISSUE THREAD

**Issue by John-Barr** [digitalec/deemon#32]
I currently have the following directory structure:
```
[Artists] /
├─ Artist_1 /
│  ├─ [YYYY-MM-DD] Release_1 /
```

However, when I use the `deemon download --artist "Artist_1"` the resulting structure is then:

```
[Artists]/
├─ Artist_1/ 
│  ├─ [YYYY-MM-DD] Release_1/
├─ Artist_1 - Release_1/
```

Meaning it won't take sub-folders into considerations and re-downloads releases.
Maybe something similar to deemix's templating system can be used?

![Templates](https://user-images.githubusercontent.com/34806546/129328263-ac2d44ac-0cb7-468c-9111-4113423fa171.png)

The fields used can be found in the `config.json`:

```
"tracknameTemplate": "%artist% - %title%",
"albumTracknameTemplate": "%tracknumber% - %title%",
"albumNameTemplate": "[%date%] %album%",
```

**Comment by digitalec** [comment]
If you don't specify a path to the folder containing your deemix config ("deemix_path"), it uses the default path. If the tags don't match your settings in the deemix GUI, then you are most likely not using the same deemix config file.

**Comment by John-Barr** [comment]
Oh jeez that is my bad, you are correct I had it set to an old config... 
Great work on your end to know what the problem was even though I didn't give you much info, props!

Cheers!
