### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by myrko1337** [digitalec/deemon#38]
Hey probably a dumb question, but if i added by_release_date=false in my config and then monitor a new artist shouldn't it download everything from this artist?
Because i am not getting any downloads.

**Comment by digitalec** [comment]
No. Setting `by_release_date` to False will just ignore the release date of new releases (useful if Deezer adds some back catalog). What you're looking for is `--download`. Take a look at `deemon monitor -h` for more.
