### ISSUE TITLE
How do we restore from backup?

### ISSUE THREAD

**Issue by mathiasfoster** [digitalec/deemon#52]
I have a .tar file that is a backup of my Deemon settings (prior to resetting my computer).
How do I restore from backup?

I looked through any documentation I could find, but couldn't see it anywhere!

**Comment by digitalec** [comment]
Documentation is a bit dated, sorry. I definitely need to get to that.

You can restore a backup using `deemon backup --restore`. You can also use `--help` with any command to see how you can use it/what options are available to you.
