### ISSUE TITLE
deemon config ARTIST writes Download Path in lowercase

### ISSUE THREAD

**Issue by kirkjne** [digitalec/deemon#67]
This causes problems on linux systems because it changes the path.

**Comment by gradiian** [comment]
Can you elaborate on this? What command did you run and what did it do? What did you expect it to do instead?

**Comment by digitalec** [comment]
Can you elaborate on this to better help me reproduce it?

What command did you run exactly?

What was the output of that command?

What did you expect to happen?

**Comment by kirkjne** [comment]
First I run `deemon monitor --artist-id 843`. That is ok. Then I run `deemon config 843` and fill in the following data:
```
deemon Artist Configurator
:: Configuring 'Audioslave' (Artist ID: 843)

Bitrate [None]:
Record Type [None]:
Alerts [None]:
Download Path [None]: /home/user/Music/A/

:: Save these settings? [y|N] y

Artist 'Audioslave' has been updated!
```
But when I run the command `deemon config 843` again, it returns the following:
```
deemon Artist Configurator
:: Configuring 'Audioslave' (Artist ID: 843)

Bitrate [None]:
Record Type [None]:
Alerts [None]:
Download Path [/home/user/music/a/]:
```
`/home/user/Music/A/` was recorded as `/home/user/music/a/`.

**Comment by digitalec** [comment]
Bug confirmed
