### ISSUE TITLE
deemon refresh ignoring the download path configured with deemon config ARTIST

### ISSUE THREAD

**Issue by kirkjne** [digitalec/deemon#68]
Even with the download path configured in the artist, it downloads to the location configured in the global configuration

**Comment by digitalec** [comment]
I will look into this. What version are you using? Does the download path specified for the artist already exist?

**Comment by kirkjne** [comment]
Version 2.10.
The location in the config is /home/user/music/a/ and I created the /home/user/music/a/ folder.
Do I need to create the folder with the artist's name?

**Comment by digitalec** [comment]
Nope, deemix creates the directories when it downloads as long as the `download_path` exists. I'll take a look, thanks for the info!

**Comment by digitalec** [comment]
Bug confirmed

**Comment by digitalec** [comment]
Thanks for reporting this and #67. I discovered that _all_ per-artist settings were being ignored and have resolved both of your reported issues. I just uploaded `2.10.1` but please let me know if there's any further issues.
