### ISSUE TITLE
--no-refresh now working

### ISSUE THREAD

**Issue by Net-Felix** [digitalec/deemon#76]
when i use ```deemon monitor --no-refresh --record-type album --artist-id xxx```
i only get error message: ```Error: No such option: --no-refresh```

**Comment by digitalec** [comment]
`--no-refresh` was removed in an earlier release since you can now monitor a batch of artists at once. Documentation needs to be updated but I always recommend using `--help` on a command to see usage and examples: `deemon monitor --help`
