### ISSUE TITLE
Unmonitor a playlist

### ISSUE THREAD

**Issue by mathiasfoster** [digitalec/deemon#78]
Thanks for creating this project!
I have several playlists that Deemon monitors, and I'd like to stop monitoring several of them.
I couldn't see (in the documentation) how I could do this, is there a command similar to `deemon monitor --remove`?

**Comment by digitalec** [comment]
Yes, it should be `deemon monitor --remove --playlist URL`. If it doesn't work, let me know and I'll have a look. I haven't had time to update the documentation in a while but it's on my list of things to do (eventually... lol)
