### ISSUE TITLE
Artists with lower case name are skipped

### ISSUE THREAD

**Issue by theruleof4** [digitalec/deemon#8]
Hi, I just notice that artists with lower cases are not recognized by Deemon. I have in a folder, names like eRa, black midi, which is this way they are written and the program just ignores them when will search for new releases, I mean, it's just skipped even for register in the database. For example, I have these sequence folders:

```
Artist X
Artist Y
black midi
Artist Z

And when will check for new releases, show me this way:

```

```
Checking for new releases...

Artist X
Artist Y
Artist Z

```

Edit. I've closed because I thought that was not a problem but seems it is.

After it checked all the artists, and skipped the artists with lower case, at the end has this message: 

a-ha: 0 release(s)
ana roxanne: 0 release(s)
black midi: 0 release(s)
eRa: 0 release(s)
exael: 0 release(s)
juneunit: 0 release(s)
rRoxymore: 0 release(s)
sphontik: 0 release(s)
t e l e p a t h テレパシー能力者: 0 release(s)
the Maccabees: 0 release(s)
uon: 2 release(s)
virginia aveline: 0 release(s)
тпсб: 0 release(s)
⣎⡇ꉺლ༽இ•̛)ྀ◞ ༎ຶ ༽ৣৢ؞ৢ؞ؖ ꉺლ: 0 release(s)
２８１４: 0 release(s)

Purged 12 artist(s) from database

I believe it just ignoring these artists for some reason but is that the way the artists are named, including in the Deezer itself.

**Comment by theruleof4** [comment]
For example, the artist "uon" who has 2 new releases, was not downloaded.

**Comment by digitalec** [comment]
Was this the first time deemon saw "uon"?

**Comment by theruleof4** [comment]
What do you mean? The artist "uon" was in my folder since the first time I used Deemon, but just now I've noticed that was ignored. 
Actually, the only new artist on this list is "black midi" that I added last week and Deemon would have to update a new release this week, since there was a new album last friday, but this not happened. All the other artists deemon should saw since the first time I used, but I just noticed now since black midi was not updated.

**Comment by digitalec** [comment]
Can you attach your releases.db file so I can take a further look?

**Comment by theruleof4** [comment]
Yes, here it is
[releases.zip](https://github.com/digitalec/deemon/files/6567470/releases.zip)

**Comment by digitalec** [comment]
I checked for black midi (artist id is `12929461`) and their newest release from last week, Cavalcade (album id is `228234412`) and it was seen and recorded by deemon in it's database:

![Screenshot from 2021-05-31 09-40-33](https://user-images.githubusercontent.com/31838395/120202239-607e4100-c1f4-11eb-9e9a-304a4a9f2533.png)

If you added black midi after their release was listed on Deezer (released or not) deemon would not have picked it up. Some artists' albums show up before release (for pre-save purposes) and deemon does not (yet) know how to handle this.

deemon/Deezer doesn't care about case sensitivity so lower case artists names make no difference. deemon searches Deezer via the API for the artist's name and returns the first result. Some artists have multiple different artist IDs and some artists share the same ID.

If you need more help, please feel free to reopen this issue.

**Comment by theruleof4** [comment]
I see, maybe with black midi was this case that shows up early. But what the message "Purged 12 artist(s) from database" means?

And what about the artist "uon" who was detected new releases but not downloaded them?

**Comment by digitalec** [comment]
"Purged 12 artists from database" means that it is no longer monitoring 12 artists because they are no longer being passed to do deemon.


For example, let's say I have these folders:

'''
Music/
  ArtistA
  ArtistB
  ArtistC
'''


If I run `deemon -a Music` it'll record all releases by each of those artists but won't download any the first time it sees a new artist (unless `-D` is used). If I delete one of the artist folders, the next time it runs you'll see "Purged 1 artist from database" because the artist is no longer there so it won't continue monitoring it.

The UI isn't very intuitive and in the next release it will be replaced with more natural commands.

The artist "uon" won't download those two releases because it's the first time deemon saw it. The next time "uon" releases something on Deezer, it will detect it as a "new release".

**Comment by theruleof4** [comment]
Well, this is weird because I not removed any artist from my folder, just added, but just a few, It's not even close to 12, another thing, "uon" was  in the library since I tried deemon, its a very old folder
