### ISSUE TITLE
Possible to disable download?

### ISSUE THREAD

**Issue by kkatayama** [digitalec/deemon#87]
I would like to set up deemon to monitor Artists and get Email notifications, but I don't want it to automatically download anything.

I was thinking of setting the `deemix` path to `/dev/null`.

```json
    "deemix": {
        "path": "/dev/null",
        "arl": "",
        "check_account_status": false
    },
```

Would this work, or should I go about this with a different approach?

**Comment by digitalec** [comment]
This can be achieved using `deemon refresh --skip-download`.

**Comment by kkatayama** [comment]
OMG, I am so sorry I didn't see that in the docs.

**Comment by digitalec** [comment]
Not a problem!
