### ISSUE TITLE
Receiving ARL error

### ISSUE THREAD

**Issue by torres3490** [digitalec/deemon#9]
Receiving "ARL verification failed" Checked ARL in Deemix software and it works fine... / Am I suppose to input ARL into Deemon files somehow??
![Screenshot_20210602-183845](https://user-images.githubusercontent.com/9975982/120566028-50c15100-c3dc-11eb-837a-08fa346f408f.jpg)

**Comment by digitalec** [comment]
Your ARL is only valid for 90 days so before deemon tries to do anything, it checks to make sure it's still good. It passes your ARL into deemix and gets a True (successful login) or False (failed login or ARL file is missing) back. By default, deemon uses the default deemix path for your config settings which on Windows is `%appdata%\deemon`.

1. Did you run deemix with the portable flag set?

2. If you run deemix, does it prompt for an ARL?

3. If you pass a URL to deemix, does it download it?

Also, if you're using the web UI (deemix-pyweb), you still need to configure deemix on the command line by running "deemix".
