### ISSUE TITLE
Deemon stops the download when a release is not available

### ISSUE THREAD

**Issue by Ruke805** [digitalec/deemon#91]
During the Refresh command, one of the releases is not available in my country, it shows the error message:

` [!] Error while downloading XXXXXX by XXXXXXX: Your account can't stream the track from your current country and no alternative found.`

```
[X] Exiting due to halt_download_on_error
:: Downloading release 48 of 61...  77%
```

The remaining releases are not downloaded and there is no option to skip this unavailable release

**Comment by digitalec** [comment]
You can disable `halt_download_on_error` in your config. This was added in one of the latest releases as default to True but will be reversed to avoid confusion in the next release.

**Comment by Ruke805** [comment]
Thanks for answer. 
Where can I edit the the config file?

**Comment by digitalec** [comment]
That depends on which OS you're using. They are all listed here: https://digitalec.github.io/deemon/docs/configuration.html#configuration-location
