### ISSUE TITLE
Archive option similar to yt-dlp --download-archive

### ISSUE THREAD

**Issue by AKL55** [digitalec/deemon#96]
Is there any way to avoid redownloading deleted files?
If not it would be nice to have in the future, this way we can delete the files or move then to another folder, and not redownload when updating artist.

**Comment by digitalec** [comment]
deemon is database-based, not file based. If you delete a file, it doesn't know. It will only download release IDs it has not seen yet. Sometimes releases get re-added which is a different release ID. You can prevent those from getting downloaded by making sure `max_release_age` is set.

**Comment by AKL55** [comment]
It was a dumb feature request by me, i was using `deemon download -m` and this command redownloaded files,
using `deemon refresh` worked fine without redownloading deleted files.

**Comment by AKL55** [comment]
@digitalec quick question:
when using `deemon download -T or -u` is there a way to add the track into the database without monitoring the artist of the track\album?

**Comment by digitalec** [comment]
No, there isn't. The database is designed to track album releases and their respective artists.
